/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdSearchRouteImport } from './routes/projects/$projectId/search'
import { Route as ProjectsProjectIdGraphRouteImport } from './routes/projects/$projectId/graph'
import { Route as ProjectsProjectIdDocumentsRouteImport } from './routes/projects/$projectId/documents'
import { Route as ProjectsProjectIdChatRouteImport } from './routes/projects/$projectId/chat'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSearchRoute = ProjectsProjectIdSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdGraphRoute = ProjectsProjectIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDocumentsRoute =
  ProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdChatRoute = ProjectsProjectIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/graph': typeof ProjectsProjectIdGraphRoute
  '/projects/$projectId/search': typeof ProjectsProjectIdSearchRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/graph': typeof ProjectsProjectIdGraphRoute
  '/projects/$projectId/search': typeof ProjectsProjectIdSearchRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/graph': typeof ProjectsProjectIdGraphRoute
  '/projects/$projectId/search': typeof ProjectsProjectIdSearchRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/graph'
    | '/projects/$projectId/search'
    | '/projects/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/graph'
    | '/projects/$projectId/search'
    | '/projects/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/graph'
    | '/projects/$projectId/search'
    | '/projects/$projectId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/search': {
      id: '/projects/$projectId/search'
      path: '/search'
      fullPath: '/projects/$projectId/search'
      preLoaderRoute: typeof ProjectsProjectIdSearchRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/graph': {
      id: '/projects/$projectId/graph'
      path: '/graph'
      fullPath: '/projects/$projectId/graph'
      preLoaderRoute: typeof ProjectsProjectIdGraphRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/documents': {
      id: '/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/chat': {
      id: '/projects/$projectId/chat'
      path: '/chat'
      fullPath: '/projects/$projectId/chat'
      preLoaderRoute: typeof ProjectsProjectIdChatRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdChatRoute: typeof ProjectsProjectIdChatRoute
  ProjectsProjectIdDocumentsRoute: typeof ProjectsProjectIdDocumentsRoute
  ProjectsProjectIdGraphRoute: typeof ProjectsProjectIdGraphRoute
  ProjectsProjectIdSearchRoute: typeof ProjectsProjectIdSearchRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdChatRoute: ProjectsProjectIdChatRoute,
  ProjectsProjectIdDocumentsRoute: ProjectsProjectIdDocumentsRoute,
  ProjectsProjectIdGraphRoute: ProjectsProjectIdGraphRoute,
  ProjectsProjectIdSearchRoute: ProjectsProjectIdSearchRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
