/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as ProjectsProjectIdSearchRouteImport } from './routes/projects/$projectId/search'
import { Route as ProjectsProjectIdGraphRouteImport } from './routes/projects/$projectId/graph'
import { Route as ProjectsProjectIdChatRouteImport } from './routes/projects/$projectId/chat'
import { Route as ProjectsProjectIdDocumentsRouteRouteImport } from './routes/projects/$projectId/documents/route'
import { Route as ProjectsProjectIdDocumentsIndexRouteImport } from './routes/projects/$projectId/documents/index'
import { Route as ProjectsProjectIdDocumentsDocumentIdRouteRouteImport } from './routes/projects/$projectId/documents/$documentId/route'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSearchRoute = ProjectsProjectIdSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdGraphRoute = ProjectsProjectIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdChatRoute = ProjectsProjectIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDocumentsRouteRoute =
  ProjectsProjectIdDocumentsRouteRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDocumentsIndexRoute =
  ProjectsProjectIdDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdDocumentsRouteRoute,
  } as any)
const ProjectsProjectIdDocumentsDocumentIdRouteRoute =
  ProjectsProjectIdDocumentsDocumentIdRouteRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ProjectsProjectIdDocumentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRouteRouteWithChildren
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/graph': typeof ProjectsProjectIdGraphRoute
  '/projects/$projectId/search': typeof ProjectsProjectIdSearchRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRouteRoute
  '/projects/$projectId/documents/': typeof ProjectsProjectIdDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/graph': typeof ProjectsProjectIdGraphRoute
  '/projects/$projectId/search': typeof ProjectsProjectIdSearchRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRouteRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRouteRouteWithChildren
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/graph': typeof ProjectsProjectIdGraphRoute
  '/projects/$projectId/search': typeof ProjectsProjectIdSearchRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRouteRoute
  '/projects/$projectId/documents/': typeof ProjectsProjectIdDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/graph'
    | '/projects/$projectId/search'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/documents/$documentId'
    | '/projects/$projectId/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/graph'
    | '/projects/$projectId/search'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/documents/$documentId'
    | '/projects/$projectId/documents'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/graph'
    | '/projects/$projectId/search'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/documents/$documentId'
    | '/projects/$projectId/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/search': {
      id: '/projects/$projectId/search'
      path: '/search'
      fullPath: '/projects/$projectId/search'
      preLoaderRoute: typeof ProjectsProjectIdSearchRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/graph': {
      id: '/projects/$projectId/graph'
      path: '/graph'
      fullPath: '/projects/$projectId/graph'
      preLoaderRoute: typeof ProjectsProjectIdGraphRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/chat': {
      id: '/projects/$projectId/chat'
      path: '/chat'
      fullPath: '/projects/$projectId/chat'
      preLoaderRoute: typeof ProjectsProjectIdChatRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/documents': {
      id: '/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsRouteRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/documents/': {
      id: '/projects/$projectId/documents/'
      path: '/'
      fullPath: '/projects/$projectId/documents/'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdDocumentsRouteRoute
    }
    '/projects/$projectId/documents/$documentId': {
      id: '/projects/$projectId/documents/$documentId'
      path: '/$documentId'
      fullPath: '/projects/$projectId/documents/$documentId'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsDocumentIdRouteRouteImport
      parentRoute: typeof ProjectsProjectIdDocumentsRouteRoute
    }
  }
}

interface ProjectsProjectIdDocumentsRouteRouteChildren {
  ProjectsProjectIdDocumentsDocumentIdRouteRoute: typeof ProjectsProjectIdDocumentsDocumentIdRouteRoute
  ProjectsProjectIdDocumentsIndexRoute: typeof ProjectsProjectIdDocumentsIndexRoute
}

const ProjectsProjectIdDocumentsRouteRouteChildren: ProjectsProjectIdDocumentsRouteRouteChildren =
  {
    ProjectsProjectIdDocumentsDocumentIdRouteRoute:
      ProjectsProjectIdDocumentsDocumentIdRouteRoute,
    ProjectsProjectIdDocumentsIndexRoute: ProjectsProjectIdDocumentsIndexRoute,
  }

const ProjectsProjectIdDocumentsRouteRouteWithChildren =
  ProjectsProjectIdDocumentsRouteRoute._addFileChildren(
    ProjectsProjectIdDocumentsRouteRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdDocumentsRouteRoute: typeof ProjectsProjectIdDocumentsRouteRouteWithChildren
  ProjectsProjectIdChatRoute: typeof ProjectsProjectIdChatRoute
  ProjectsProjectIdGraphRoute: typeof ProjectsProjectIdGraphRoute
  ProjectsProjectIdSearchRoute: typeof ProjectsProjectIdSearchRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdDocumentsRouteRoute:
    ProjectsProjectIdDocumentsRouteRouteWithChildren,
  ProjectsProjectIdChatRoute: ProjectsProjectIdChatRoute,
  ProjectsProjectIdGraphRoute: ProjectsProjectIdGraphRoute,
  ProjectsProjectIdSearchRoute: ProjectsProjectIdSearchRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
